baseURL = "https://holtenko.github.io"
title   = "HOLTEN KO"

DefaultContentLanguage = "zh"

theme = "hello-friend-ng"

PygmentsCodeFences = true
PygmentsStyle = "monokai"

rssLimit  = 10  # Maximum number of items in the RSS feed.
copyright = "" # This message is only used by the RSS template.

# googleAnalytics = ""
# disqusShortname = ""

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

buildDrafts  = false
buildFuture  = false
buildExpored = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = true
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[permalinks]
  posts = "/posts/:year/:month/:title/"

[author]
  name = "Holten KO"

[blackfriday]
  hrefTargetBlank = true

[taxonomies]
  tag      = "tags"
  category = "categories"

[params]
  dateform        = "Jan 2, 2015"
  yearform        = "2015"
  dateformShort   = "Jan 2"
  dateformNum     = "2015-01-02"
  dateformNumTime = "2015-01-02 15:04 +0800"

  # Metadata mostly used in document's head
  description = "Holten KO's homepage."
  keywords = ""
  images = [""]

  homeSubtitle = "Make your own way."

  # Prefix of link to the git commit detail page. GitInfo must be enabled.
  # gitUrl = ""

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = true

  # Integrate Javascript files or stylesheets by adding the url to the external assets or by
  # linking local files with their path relative to the static folder, e.g. "css/styles.css"
  customCSS = []
  customJS  = []

  # Toggle this option need to rebuild SCSS, requires extended version of Hugo
  justifyContent = false  # Set "text-align: justify" to .content.

  # Directory name of your blog content (default is `content/posts`)
  contentTypeName = "posts"

  # Default theme "light" or "dark"
  defaultTheme = "light"
  themeColor = "#252627"

  # Colors for favicons
  [params.favicon.color]
    mask = "#252627"
    msapplication = "#252627"
    theme = "#252627"

  [params.logo]
    logoText     = "$ cd /home/"
    logoHomeLink = "/"
    # Set to a valid CSS color to change the cursor in the logo.
    # logoColor    = "#67a2c9"

  # Social icons
  [[params.social]]
    name = "book"
    url  = "/blog"

  [[params.social]]
    name = "email"
    url  = "mailto:nobody@example.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/holtenko"

  [[params.social]]
    name = "stackoverflow"
    url  = "https://stackoverflow.com/users/6351396/holten"

[languages]
  [languages.zh]
    title = "HOLTEN KO"
    subtitle = "Homepage"
    homeSubtitle = "Make your own way."
    copyright = "CC BY-NC-SA 4.0"
    # readOtherPosts = "Read other posts"
    
    [languages.zh.params.logo]
    logoText = "hello holten"
    logoHomeLink = "/"
    # or
    #
    # path = "/logo-header.png"
    # alt = "Your example logo alt text"

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/blog"
